language: php

php:
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - bin/phpunit

after_script:
  - bin/coveralls

before_script:
  - composer self-update
  - composer install -n

script:
  - bin/phpspec run -fpretty --verbose
  - phpunit

notifications:
  email:
    - system+travis-ci@hmlb.fr
